const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let data=[],reviews=[],inflight=new Set();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=s=>s?new Date(s).toLocaleDateString():'—';
const badge=s=>`<span class="badge ${esc(s)}">${esc(s||'draft')}</span>`;
async function api(p,o={}){let r=await fetch('/api'+p,{headers:{'Content-Type':'application/json'},...o}),d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.detail||r.statusText);return d}
function toast(s){let t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function tab(t){$$('.tab').forEach(x=>x.classList.add('hidden'));$('#'+t).classList.remove('hidden');$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$('#crumb').textContent=({dashboard:'Dashboard',create:'Create post',posts:'All posts',schedule:'Scheduler',logs:'Activity & logs'})[t];if(t!=='dashboard')render(t)}
$$('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$$('[data-open]').forEach(b=>b.onclick=()=>tab(b.dataset.open));
function row(p){return `<div class="postrow"><div><b>${esc(p.topic||p.post_content||'Untitled')}</b><span class="muted">${esc(p.platform)} · ${dt(p.created_at)}</span></div>${badge(p.status)}</div>`}
async function load(){try{let [h,d,p]=await Promise.all([api('/health'),api('/dashboard'),api('/posts?limit=500')]);$('#health').textContent=h.database==='connected'?'● Database connected':'● DB unavailable';data=p.items||[];for(let k of ['total','pending','posted','failed'])$('#'+k).textContent=d.stats[k]??0;$('#recent').innerHTML=(d.recent||[]).map(row).join('')||'<div class="empty">No posts yet.</div>';$('#platforms').innerHTML=(d.platforms||[]).map(x=>`<div class="platformrow"><span>${esc(x.platform)}</span><span>${x.posted} published</span><b>${x.total}</b></div>`).join('')||'<div class="empty">No platform activity.</div>';let t=$$('.tab:not(.hidden)')[0]?.id;if(t&&t!=='dashboard')render(t)}catch(e){$('#health').textContent='● Connection unavailable';toast(e.message)}}
function render(t){if(t==='posts'){let q=($('#search').value||'').toLowerCase(),s=$('#filter').value,a=data.filter(p=>(!s||p.status===s)&&(`${p.topic} ${p.post_content} ${p.platform}`).toLowerCase().includes(q));$('#rows').innerHTML=a.map(p=>`<tr><td><b>${esc(p.topic)}</b><span class="muted">${esc((p.post_content||'').slice(0,70))}</span></td><td>${esc(p.platform)}</td><td>${badge(p.status)}</td><td>${dt(p.created_at)}</td><td><button class="action" onclick="edit(${p.id})">Edit</button>${p.status==='failed'?`<button class="action" onclick="retry(${p.id})">Retry</button>`:''}<button class="action" onclick="del(${p.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No posts found.</td></tr>'}if(t==='schedule'){let a=data.filter(p=>p.scheduled_at);$('#scheduled').innerHTML=a.map(p=>row(p)+`<span class="muted">${new Date(p.scheduled_at).toLocaleString()}</span>`).join('')||'<div class="empty">No scheduled posts. Set a date using Edit.</div>'}if(t==='logs'){let a=data.filter(p=>['failed','posted'].includes(p.status)).slice(0,100);$('#logrows').innerHTML=a.map(p=>row(p)+`<span class="muted">${esc(p.error_message||p.platform_post_id||'')}</span>`).join('')||'<div class="empty">No publishing activity yet.</div>'}}
$('#search').oninput=()=>render('posts');$('#filter').onchange=()=>render('posts');
window.edit=id=>{let p=data.find(x=>x.id===id);$('#eid').value=id;$('#etopic').value=p.topic||'';$('#econtent').value=p.post_content||'';$('#htags').value=p.hashtags||'';$('#eimage').value=p.image_url||'';$('#estatus').value=p.status||'pending';$('#edate').value=p.scheduled_at?new Date(p.scheduled_at).toISOString().slice(0,16):'';$('#modal').classList.remove('hidden')};
function close(){$('#modal').classList.add('hidden')}$('#close').onclick=close;
$('#save').onclick=async()=>{try{let d=$('#edate').value;await api('/posts/'+$('#eid').value,{method:'PATCH',body:JSON.stringify({topic:$('#etopic').value,post_content:$('#econtent').value,hashtags:$('#htags').value,image_url:$('#eimage').value||null,status:$('#estatus').value,scheduled_at:d?new Date(d).toISOString():null})});close();toast('Post saved');load()}catch(e){toast(e.message)}};
window.retry=async id=>{if(confirm('Reset post to pending?')){try{await api(`/posts/${id}/retry`,{method:'POST'});toast('Queued as pending');load()}catch(e){toast(e.message)}}};window.del=async id=>{if(confirm('Delete post permanently?')){try{await api(`/posts/${id}`,{method:'DELETE'});toast('Deleted');load()}catch(e){toast(e.message)}}};
function card(r){return `<article class="panel review-card" data-id="${esc(r.id)}"><div class="review-head"><div><small>${esc(r.platform)}</small><h3>${esc(r.topic)}</h3></div><span class="review-state ${esc(r.state.toLowerCase().replaceAll(' ','-'))}">${esc(r.state)}</span></div><label>Post content</label><textarea data-field="content" rows="6" ${r.busy||r.state==='Approved'?'disabled':''}>${esc(r.post_content)}</textarea><label>Hashtags</label><textarea data-field="hashtags" rows="2" ${r.busy||r.state==='Approved'?'disabled':''}>${esc(r.hashtags)}</textarea><label>Image prompt</label><textarea data-field="image_prompt" rows="2" ${r.busy||r.state==='Approved'?'disabled':''}>${esc(r.image_prompt)}</textarea><label>Image URL</label><input data-field="image_url" value="${esc(r.image_url)}" ${r.busy||r.state==='Approved'?'disabled':''}>${r.retry_count?`<small class="retry-count">Regenerated ${r.retry_count} time${r.retry_count===1?'':'s'}</small>`:''}${r.error?`<p class="review-error">${esc(r.error)}</p>`:''}${r.message?`<p class="review-message">${esc(r.message)}</p>`:''}${r.state==='Approved'?`<p class="saved-confirmation">✓ Approved and saved in database (ID ${esc(r.saved_id)}), status approved for scheduling.</p>`:`<div class="review-actions"><button class="primary" data-action="approve" ${r.busy||r.state!=='Awaiting Approval'?'disabled':''}>${r.busy&&r.busy==='saving'?'Saving…':'Approve'}</button><button class="secondary" data-action="decline" ${r.busy?'disabled':''}>Decline</button><button class="secondary" data-action="regenerate" ${r.busy?'disabled':''}>${r.busy==='regenerating'?'Regenerating…':'Retry / Regenerate'}</button></div>`}</article>`}
function drawReviews(){const root=$('#results');root.innerHTML=reviews.length?'<h2 class="review-title">Review generated posts</h2><div class="review-grid">'+reviews.map(card).join('')+'</div>':'';root.querySelectorAll('.review-card').forEach(el=>{let r=reviews.find(x=>x.id===el.dataset.id);el.querySelectorAll('[data-field]').forEach(f=>f.oninput=()=>{r[f.dataset.field]=f.value});el.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='approve')approveCard(r);if(b.dataset.action==='decline')declineCard(r);if(b.dataset.action==='regenerate')regenerateCard(r)})})}
function busy(r,what){r.busy=what;drawReviews()}
async function approveCard(r){if(inflight.has(r.id))return;inflight.add(r.id);r.error='';r.message='';busy(r,'saving');try{let d=await api('/approve',{method:'POST',body:JSON.stringify({idempotency_key:r.idempotency_key,topic:r.topic,platform:r.platform,post_content:r.post_content,hashtags:r.hashtags,image_prompt:r.image_prompt,image_url:r.image_url||null})});r.state='Approved';r.saved_id=d.id;r.message='';r.busy=false;drawReviews();await load()}catch(e){r.state='Awaiting Approval';r.error=`Approval failed: ${e.message}`;r.busy=false;drawReviews()}finally{inflight.delete(r.id)}}
function declineCard(r){if(inflight.has(r.id))return;if(!confirm(`Decline this ${r.platform} post? It will not be saved.`))return;reviews=reviews.filter(x=>x.id!==r.id);drawReviews();toast(`${r.platform} content declined; nothing was saved.`)}
async function regenerateCard(r){if(inflight.has(r.id))return;let changed=r.content!==r.post_content||r.original_hashtags!==r.hashtags||r.original_image_prompt!==r.image_prompt;if(changed&&!confirm('This post has manual edits. Replace them with regenerated content?'))return;inflight.add(r.id);r.error='';r.message='';busy(r,'regenerating');try{let d=await api('/generate',{method:'POST',body:JSON.stringify({topic:r.topic,platforms:[r.platform],image_url:r.image_url||null})}),fresh=d.posts?.find(p=>p.platform.toLowerCase()===r.platform.toLowerCase());if(!fresh)throw Error('No content returned for this platform.');r.post_content=fresh.post_content;r.hashtags=fresh.hashtags||'';r.image_prompt=fresh.image_prompt||'';r.content=r.post_content;r.original_hashtags=r.hashtags;r.original_image_prompt=r.image_prompt;r.retry_count++;r.state='Awaiting Approval';r.error='';r.message='Content regenerated successfully.'}catch(e){r.error=`Regeneration failed; the previous content was kept. ${e.message}`}finally{r.busy=false;inflight.delete(r.id);drawReviews()}}
$('#generate').onclick=async()=>{let topic=$('#topic').value.trim(),platforms=$$('.checks input:checked').map(x=>x.value),image_url=$('#image').value.trim(),b=$('#generate');if(!topic||!platforms.length){$('#genmsg').textContent='Enter a topic and select a platform.';return}b.disabled=true;b.textContent='Generating…';$('#genmsg').textContent='';try{let d=await api('/generate',{method:'POST',body:JSON.stringify({topic,platforms,image_url:image_url||null})});reviews=d.posts.map((p,i)=>({id:`${Date.now()}-${i}-${Math.random()}`,idempotency_key:crypto.randomUUID(),topic,platform:p.platform,post_content:p.post_content,hashtags:p.hashtags||'',image_prompt:p.image_prompt||'',image_url,retry_count:0,state:'Awaiting Approval',busy:false,content:p.post_content,original_hashtags:p.hashtags||'',original_image_prompt:p.image_prompt||'',error:'',message:''}));drawReviews();$('#genmsg').textContent=`Generated ${reviews.length} post${reviews.length===1?'':'s'}. Review each platform before saving.`}catch(e){$('#genmsg').textContent=e.message}finally{b.disabled=false;b.textContent='✳ Generate content'}};
$('#refresh').onclick=load;load();
